### ISSUE TITLE
Provide a UI card that displays the water heater

### ISSUE THREAD

**Issue by danielgospodinow** [qbaware/homeassistant-eldom#36]
Similar to what we have in HA for climate entities:

![Image](https://github.com/user-attachments/assets/52db4930-66c2-4b0d-9f7b-8d0f87ae72ea)

Discord: https://discord.com/channels/1312381782942810192/1312386863947972720/1341090043149811845

**Comment by danielgospodinow** [comment]
This custom tile is also not bad, tbh.

```yaml
features:
  - type: target-temperature
  - type: water-heater-operation-modes
    operation_modes:
      - "off"
      - eco
      - electric
      - high_demand
type: tile
entity: water_heater.flat_boiler_edab63cb2b9c
color: primary
name: Flat Boiler
hide_state: false
show_entity_picture: false
vertical: true
state_content:
  - state
  - last-changed

```

<img width="255" alt="Image" src="https://github.com/user-attachments/assets/3d461fe5-103e-4aca-a4ad-edc89cd9ef63" />

Upon clicking this, it opens the default HA water heater card.
